In [1]:
import numpy as np

In [2]:
a = np.array([])

In [3]:
a

array([], dtype=float64)

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9 ,10])

In [5]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9 ,10])

In [7]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[0]

1

In [9]:
arr[-1]

10

In [10]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [11]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [12]:
a[0]

array([1, 2, 3, 4])

In [13]:
a[-1]

array([ 9, 10, 11, 12])

In [14]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [15]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [16]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [17]:
print(np.arange(4))
print(np.arange(0,10,2))

[0 1 2 3]
[0 2 4 6 8]


In [18]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

In [19]:
arr = np.array([1,2,3,4,5,6,7,8])

In [20]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [21]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [22]:
arr = np.array([2,1,5,3,7,4,6,8])

In [23]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
array_example = np.array([[[0,1,2,3],
                           [4,5,6,7]],[[0,1,2,3],
                           [4,5,6,7]],[[0,1,2,3],
                           [4,5,6,7]]
                         ])

In [25]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [26]:
array_example.ndim

3

In [27]:
array_example.size

24

In [28]:
array_example.shape

(3, 2, 4)

In [29]:
arr_one = np.array([[1,2,3,4,5]])

In [30]:
arr_one.ndim

2

In [31]:
arr_one.size

5

In [32]:
arr_one.shape

(1, 5)

In [33]:
a = np.arange(6)

In [34]:
print(a)

[0 1 2 3 4 5]


In [35]:
b = a.reshape(3,2)

In [36]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [37]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [38]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [39]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [40]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [41]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [42]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [43]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [46]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [47]:
data = np.array([1,2,3])

In [48]:
print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [49]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [51]:
five_up = (a >= 5)

print(a[five_up])
print(a[a >= 5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [52]:
divisible_by_2 = a[a%2 == 0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [54]:
c = a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [55]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [56]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [57]:
a_1 = np.array([[1,1],[2,2]])

In [58]:
a_2 = np.array([[3,3],[4,4]])

In [59]:
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [60]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [61]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
                    [13,14,15,16,17,18,19,20,21,22,23,24]])
print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [62]:
np.hsplit(arrsplit, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [65]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
a = np.array([1,2,3,4])
a.sum()

10

In [69]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [70]:
b.sum(axis=0)

array([3, 3])

In [71]:
b.sum(axis=1)

array([2, 4])

In [72]:
data = np.array([1,2])
data

array([1, 2])

In [73]:
ones = np.ones(2)
ones

array([1., 1.])

In [74]:
data + ones

array([2., 3.])

In [75]:
data * data

array([1, 4])

In [76]:
data / data

array([1., 1.])

In [77]:
data * 2

array([2, 4])

In [78]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
          [0.54627315, 0.05093587, 0.40067661, 0.55645993],
          [0.12697628, 0.82485143, 0.26590556, 0.5691701]
])
print(A)



[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.5691701 ]]


In [79]:
A.min()

0.05093587

In [80]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [81]:
A.min(axis=1)

array([0.17296777, 0.05093587, 0.12697628])

In [82]:
A.max()

0.82485143

In [83]:
A.max(axis=0)

array([0.54627315, 0.82485143, 0.40067661, 0.5691701 ])

In [84]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [85]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [87]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [88]:
np.ones((2,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [89]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [90]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [91]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [92]:
data = np.array([[1,2], [3,4]])

In [93]:
print(data)

[[1 2]
 [3 4]]


In [94]:
ones = np.ones([2,2])

In [95]:
print(ones)

[[1. 1.]
 [1. 1.]]


In [96]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [97]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [98]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


In [99]:
a_1 = np.array([[1,2,3], [4,5,6]])

In [100]:
print(a_1)

[[1 2 3]
 [4 5 6]]


In [101]:
print(a_1.shape)

(2, 3)


In [102]:
a_2 = np.array([[7,8], [9,10], [11, 12]])

In [103]:
print(a_2)

[[ 7  8]
 [ 9 10]
 [11 12]]


In [104]:
print(a_2.shape)

(3, 2)


In [105]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [106]:
data = np.array([[1,2], [3,4], [5,6]])

In [107]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [108]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [109]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [110]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [111]:
data.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [112]:
data.reshape(2,4)

ValueError: cannot reshape array of size 6 into shape (2,4)

In [113]:
data.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [114]:
ndarr = np.array([[[1,2], [3, 4]], [[5,6],[7,8]]])

In [115]:
print(ndarr)
ndarr.shape

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


(2, 2, 2)

In [116]:
print(np.random.random((4,3,2)))

[[[0.40259218 0.70968983]
  [0.04505701 0.78546037]
  [0.4576109  0.66610763]]

 [[0.72565262 0.475177  ]
  [0.62119438 0.39327701]
  [0.32553132 0.12274478]]

 [[0.66714738 0.21793843]
  [0.17575199 0.88667846]
  [0.03822917 0.6627918 ]]

 [[0.72778874 0.50001341]
  [0.55865771 0.4613378 ]
  [0.15014526 0.50514587]]]


In [117]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [118]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [119]:
n = 10
observed = 100
prediction = 200
error = (1/n) * np.sum(np.square(observed - prediction))

In [120]:
print(error)

1000.0
